name: Push Docker image to Github Packages (GHCR)

on:
  push:
    branches:
      - master

jobs:
  packaging:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/sunny-unik/node-in-docker .

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u Sunny-unik --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/sunny-unik/node-in-docker
