name: Deploy Docker image to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t node-in-docker .

      - name: Push Docker image
        run: docker push ghcr.io/sunny-unik/node-in-docker:latest

      - name: Deploy Docker image to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
